# Generated by Django 5.2.10 on 2026-01-22 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_alter_transaction_created_at_alter_transaction_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='file1',
            field=models.FileField(blank=True, null=True, upload_to='files/'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='file2',
            field=models.FileField(blank=True, null=True, upload_to='files/'),
        ),
    ]
