# Generated by Django 5.2.10 on 2026-01-22 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_transaction_file1_transaction_file2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='file1',
            field=models.FileField(upload_to='files/'),
        ),
    ]
