# Generated by Django 5.2.10 on 2026-01-23 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='cpf_cnpj',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
